apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:    # Need to add Secret Name for Image pull from Aws ECR to Kubernetes Cluster
      - name: aws-ecr 
      containers:
      - name: container-frontend
        image: 381492085690.dkr.ecr.ap-south-1.amazonaws.com/dev:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: frontend
spec:
  type: LoadBalancer
  #type: NodePort
  ports:
  - port: 80
  #nodePort: 30001
  selector:
    app: frontend
