pipeline {
   agent any

    stages {
        stage('Git Checkout') {
            steps {
            script{
                git branch: 'dev', credentialsId: 'GitHub', url: 'https://github.com/papunabiswal/mrsoft_frontend.git'  
                }  
            }
        }
        stage('Update Manifest'){
            steps {
            script{
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    //withCredentials([gitUsernamePassword(credentialsId: 'github', gitToolName: 'Default')]) {
   
                    withCredentials([usernamePassword(credentialsId: 'GitHub', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                        sh "git config user.email papunabiswal3@gmail.com"
                        sh "git config user.name papunabiswal"
                        sh "git switch dev"
                        sh "cat deployment.yaml"
                        sh "sed -i 's+547013421517.dkr.ecr.ap-south-1.amazonaws.com/mrsoftfrontend.*+547013421517.dkr.ecr.ap-south-1.amazonaws.com/mrsoftfrontend:${DOCKERTAG}+g' deployment.yaml"
                        sh "cat deployment.yaml"
                        sh "git add ."
                        sh "git commit -m 'Done by Jenkins Job changemanifest: ${env.BUILD_NUMBER}'"
                        sh "git push --force https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/mrsoft_frontend.git HEAD:dev"
                        //sh "git push https://github.com/srikanta1219/update-k8s-manifest.git"
                        
                    }
                }
            }
        }    
            
    }
  
   }
}
